### ISSUE TITLE
Enable module features

### ISSUE THREAD

**Issue by mpolano** [mzagozen/notconf#7]
First of all many thanks for sharing this work !
Is there a way to enable module features or I have to modify the logic for script `install-yang-modules.sh` ?

**Comment by mzagozen** [comment]
So far I have not needed it. After giving it some thought I came up with two options:
1. Enable features selectively per container instance, like start off with a composed image containing a set of YANG modules and start *container1* and *container2* using the same image, but only enable a feature in *container1* In that case it makes sense to support features as runtime arguments, like `docker run -d --name container1 notconf_test --enable-feature feature1`.
2. Make feature selection more permanent (part of the composed image) by listing the features enable in a file in the mounted `/yang-modules` directory. This (`enable-feature.txt`? file) would be placed next to the YANG modules to be installed and optional startup configuration and operational data. 

In any case, `install-yang-modules.sh` would be the right place to do it. We can append any number of `--enable-feature feature-foo` arguments to `sysrepoctl --install module-bar ...` for option 2, or add some extra commands to change already installed modules for option 1.

WDYT?

**Comment by mpolano** [comment]
I am wondering if option 1 is feaseable. I am not expert of sysrepo but I know that it is not always possible to enable features dynamically.

For my use case option 2 would be fine. Given that each feature must be paired with the corresponding module, the configuration file `enable-feature.txt` should have a format to convey this information. \
I am thinking to a simple csv file with one feature per line. Each line with module name as first field and feature name as second field.

This would be easy to process in a bash loop where a command like this would be issued for each line:

`sysrepoctl --change <module-name> --enable-feature <feature-name>`

If you agree on this proposal I could contribute with pull request.

**Comment by mzagozen** [comment]
Sounds good, go for it!

**Comment by mzagozen** [comment]
And it's merged 🥳
